// <auto-generated />
using System;
using FileEncryption.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileEncryption.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250514143350_new-db")]
    partial class newdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FileEncryption.Core.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("EncryptedUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("FileEncryption.Core.Entities.Share", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FileKey")
                        .HasColumnType("int");

                    b.Property<string>("RecipientEmail")
                        .HasColumnType("longtext");

                    b.Property<int?>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<int>("SharedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("Used")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileKey");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("SharedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("FileEncryption.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsAdmin")
                        .HasMaxLength(20)
                        .HasColumnType("tinyint(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FileEncryption.Core.Entities.File", b =>
                {
                    b.HasOne("FileEncryption.Core.Entities.User", "UserCreated")
                        .WithMany("Files")
                        .HasForeignKey("CreatedBy");

                    b.Navigation("UserCreated");
                });

            modelBuilder.Entity("FileEncryption.Core.Entities.Share", b =>
                {
                    b.HasOne("FileEncryption.Core.Entities.File", "File")
                        .WithMany("Shares")
                        .HasForeignKey("FileKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileEncryption.Core.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FileEncryption.Core.Entities.User", "SharedByUser")
                        .WithMany()
                        .HasForeignKey("SharedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileEncryption.Core.Entities.User", null)
                        .WithMany("SharesToOthers")
                        .HasForeignKey("UserId");

                    b.HasOne("FileEncryption.Core.Entities.User", null)
                        .WithMany("SharesWithMe")
                        .HasForeignKey("UserId1");

                    b.Navigation("File");

                    b.Navigation("RecipientUser");

                    b.Navigation("SharedByUser");
                });

            modelBuilder.Entity("FileEncryption.Core.Entities.File", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("FileEncryption.Core.Entities.User", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("SharesToOthers");

                    b.Navigation("SharesWithMe");
                });
#pragma warning restore 612, 618
        }
    }
}
