import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import SecurityFeatures from "./SecuirtyFeateras";
import EncryptionSteps from "./EncraptionSteps";
import CTASection from "./CTASection";
import TestimonialsSection from "./TestimonialsSection";
import HeroSection from "./HeroSection";
import StatsSection from "./StatsSection";
const HomePage = () => {
    return (_jsx("div", { className: "min-h-screen", children: _jsxs("main", { className: "container mx-auto px-4 py-16 max-w-7xl", children: [_jsx(HeroSection, {}), _jsx(StatsSection, {}), _jsxs("section", { className: "mb-32", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.6 }, className: "text-center mb-16", children: [_jsx("div", { className: "inline-flex items-center gap-2 px-4 py-2 bg-emerald-50 rounded-full border border-emerald-100 mb-6", children: _jsx("span", { className: "text-emerald-700 text-sm font-medium", children: "Security First" }) }), _jsxs("h2", { className: "text-4xl lg:text-5xl font-bold text-gray-900 mb-6", children: ["Advanced Security", " ", _jsx("span", { className: "bg-gradient-to-r from-emerald-600 to-emerald-800 bg-clip-text text-transparent", children: "Features" })] }), _jsx("p", { className: "text-gray-600 text-xl max-w-3xl mx-auto", children: "Our encryption system uses cutting-edge technology to ensure your files remain private and secure" })] }), _jsx(SecurityFeatures, {})] }), _jsxs("section", { className: "mb-32", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.6 }, className: "text-center mb-16", children: [_jsx("div", { className: "inline-flex items-center gap-2 px-4 py-2 bg-amber-50 rounded-full border border-amber-100 mb-6", children: _jsx("span", { className: "text-amber-700 text-sm font-medium", children: "Simple Process" }) }), _jsxs("h2", { className: "text-4xl lg:text-5xl font-bold text-gray-900 mb-6", children: ["How It", " ", _jsx("span", { className: "bg-gradient-to-r from-amber-600 to-orange-600 bg-clip-text text-transparent", children: "Works" })] }), _jsx("p", { className: "text-gray-600 text-xl max-w-3xl mx-auto", children: "Our advanced encryption process is simple to use yet extremely secure" })] }), _jsx(EncryptionSteps, {})] }), _jsx(TestimonialsSection, {}), _jsx(CTASection, {})] }) }));
};
export default HomePage;
