import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import EncryptionVisualizer from "./EncraptionVizualer";
import Logo from "./Logo";
import { Button } from "@/styles/ui/button";
import EncryptionSteps from "./EncraptionSteps";
import SecurityFeatures from "./SecuirtyFeateras";
import { Upload } from "lucide-react";
const Home = () => {
    return (_jsx("div", { className: "min-h-screen bg-gradient-to-br from-gray-50 to-stone-50", children: _jsxs("main", { className: "container mx-auto px-4 py-12 max-w-7xl", children: [_jsxs("section", { className: "flex flex-col md:flex-row items-center justify-between gap-12 mb-24", children: [_jsx("div", { className: "max-w-xl", children: _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.2 }, className: "mb-6", children: [_jsx("div", { className: "flex items-center gap-3 mb-4", children: _jsx(Logo, {}) }), _jsx("h1", { className: "text-4xl md:text-5xl font-bold text-gray-900 tracking-tight mb-6", children: "Advanced File Encryption System" }), _jsx("p", { className: "text-gray-600 text-lg leading-relaxed mb-8", children: "Protect your organization's most sensitive documents with powerful encryption, custom file access, and secure, time-limited sharing. Take full control over who can view, download, or share your data \u2014 with complete visibility and security." }), _jsxs("div", { className: "flex flex-wrap gap-4", children: [_jsxs(Button, { size: "lg", className: "bg-emerald-700 hover:bg-emerald-800 text-white", onClick: () => { }, children: [_jsx(Upload, { className: "mr-2 h-5 w-5" }), "Select File"] }), _jsx(Button, { size: "lg", variant: "outline", className: "border-emerald-700 text-emerald-700 hover:bg-emerald-50", children: "Learn More" })] })] }) }), _jsx("div", { className: "w-full md:w-1/2", children: _jsx(motion.div, { initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, transition: { delay: 0.4 }, children: _jsx(EncryptionVisualizer, {}) }) })] }), _jsxs("section", { className: "mb-24", children: [_jsxs("div", { className: "text-center mb-12", children: [_jsx("h2", { className: "text-3xl font-bold text-gray-900 mb-4", children: "Advanced Security Features" }), _jsx("p", { className: "text-gray-600 max-w-2xl mx-auto", children: "Our encryption system uses cutting-edge technology to ensure your files remain private and secure" })] }), _jsx(SecurityFeatures, {})] }), _jsxs("section", { className: "mb-24", children: [_jsxs("div", { className: "text-center mb-12", children: [_jsx("h2", { className: "text-3xl font-bold text-gray-900 mb-4", children: "How It Works" }), _jsx("p", { className: "text-gray-600 max-w-2xl mx-auto", children: "Our advanced encryption process is simple to use yet extremely secure" })] }), _jsx(EncryptionSteps, {})] })] }) }));
};
export default Home;
