import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Alert, AlertDescription } from "@/styles/ui/alert";
import { Send, Loader2, AlertTriangle } from "lucide-react";
import { TabsContent } from "@/styles/ui/tabs";
import SharedSentItemCard from "./SharedSentItemCard";
import { useAppSelector } from "@/hooks";
import { motion } from "framer-motion";
import { useShareFilters } from "@/features/useShareFilters";
import ShareStats from "./ShareStats";
import ShareSearchAndFilter from "./ShareSearchAndFilter";
const SentShares = () => {
    const { sharesToOthers, status, error } = useAppSelector((state) => state.share);
    const { searchTerm, setSearchTerm, sortBy, setSortBy, sortOrder, toggleSortOrder, filterStatus, setFilterStatus, filteredAndSortedShares, resetFilters, } = useShareFilters(sharesToOthers, 'sent');
    return (_jsxs(TabsContent, { value: "sent", className: "mt-0", children: [error.fetchToOthers && (_jsxs(Alert, { variant: "destructive", className: "mb-6 border-red-200 bg-red-50", children: [_jsx(AlertTriangle, { className: "h-4 w-4" }), _jsx(AlertDescription, { children: typeof error.fetchToOthers === "string" ? error.fetchToOthers : "Failed to load shared files." })] })), status.fetchToOthers === "loading" ? (_jsxs("div", { className: "flex flex-col justify-center items-center py-16", children: [_jsx("div", { className: "p-4 rounded-full bg-orange-100 mb-4", children: _jsx(Loader2, { className: "w-8 h-8 animate-spin text-orange-600" }) }), _jsx("span", { className: "text-lg font-medium text-gray-700", children: "Loading your shared files..." }), _jsx("span", { className: "text-sm text-gray-500 mt-1", children: "Please wait a moment" })] })) : sharesToOthers.length > 0 ? (_jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { duration: 0.3 }, children: [_jsx(ShareStats, { shares: sharesToOthers, type: "sent" }), _jsx(ShareSearchAndFilter, { searchTerm: searchTerm, onSearchChange: setSearchTerm, sortBy: sortBy, onSortChange: setSortBy, sortOrder: sortOrder, onSortOrderToggle: toggleSortOrder, filterStatus: filterStatus, onFilterStatusChange: setFilterStatus, onReset: resetFilters, totalShares: sharesToOthers.length, filteredShares: filteredAndSortedShares.length, shareType: "sent" }), filteredAndSortedShares.length === 0 ? (_jsx("div", { className: "text-center py-16", children: _jsx("p", { className: "text-gray-500 text-lg", children: "No shares match your search criteria" }) })) : (_jsx("ul", { className: "space-y-4", children: filteredAndSortedShares.map((share, index) => (_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.3, delay: index * 0.05 }, children: _jsx(SharedSentItemCard, { share: share }) }, share.id))) }))] })) : (_jsxs(motion.div, { initial: { opacity: 0, scale: 0.95 }, animate: { opacity: 1, scale: 1 }, transition: { duration: 0.3 }, className: "text-center py-16", children: [_jsx("div", { className: "p-6 rounded-full bg-orange-100 w-fit mx-auto mb-6", children: _jsx(Send, { className: "h-12 w-12 text-orange-400" }) }), _jsx("h3", { className: "text-xl font-semibold text-gray-800 mb-2", children: "No files shared yet" }), _jsx("p", { className: "text-gray-500 max-w-md mx-auto", children: "Files you share with others will appear here. Start sharing to collaborate with your team!" })] }))] }));
};
export default SentShares;
